# file: .github/dependabot.yml
# version: 1.1.0
# guid: 05ea88f5-7ada-4418-875e-7f3151d2de5e
# last-edited: 2026-07-16

version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly
      day: tuesday
      time: "10:00"
      timezone: America/New_York
    labels:
      - dependencies
      - dependabot
    commit-message:
      prefix: deps
      include: scope

updates:
  # Docker
  - package-ecosystem: docker
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    labels:
      - containers

  # Github Actions
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    labels:
      - github-actions
      - ci-cd